### ISSUE TITLE
Ember with JAVA REST integration

### ISSUE THREAD

**Issue by DilipChhugani** [JanGorman/ember-by-example#1]
I would like to request you to please share Ember integration with JAVA REST API. 
I am new to EmberJs. I have started implementing some sample application based on CRUD operations using Ember CLI and Atom, but I am facing problem while integrating with JAVA REST API. Can anybody share complete example for Ember integration with JAVA REST using Eclipse/IntelliJ.

**Comment by JanGorman** [comment]
Sorry, this repo is 4 years old and uses an ancient version of ember. I suggest looking some place else.
